### ISSUE TITLE
convert phylip to nexus nchar set to ntax

### ISSUE THREAD

**Issue by MikeWLloyd** [ODiogoSilva/ElConcatenero#1]
Converting from a phylip file to a nexus file, the ntax and nchar statements are set to the same number. 

In my case, dimensions 'ntax=408 nchar=408;' should (if I understand the format correctly) read 'dimensions ntax=408 nchar=217334;'

**Comment by ODiogoSilva** [comment]
Fixed via https://github.com/ODiogoSilva/ElConcatenero/commit/f3e02aa6c6fa1f888a059c4e036661934ce316bc . Many thanks!
